[package]
name = "passumamma"
version = "0.1.0"
edition = "2021"
authors = ["Eelis Rossi"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_seeder = "0.2.3"
